"""empty message

Revision ID: be073ec8a39d
Revises:
Create Date: 2020-03-10 21:09:45.884540

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be073ec8a39d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('user_id', postgresql.UUID(), autoincrement=False,
                  nullable=False),
        sa.Column('username', sa.VARCHAR(), autoincrement=False,
                  nullable=False),
        sa.Column('_password', sa.VARCHAR(length=128), autoincrement=False,
                  nullable=False),
        sa.Column('is_superadmin', sa.BOOLEAN(), autoincrement=False,
                  nullable=False),
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False,
                  nullable=False),
        sa.Column('is_anonymous', sa.BOOLEAN(), autoincrement=False,
                  nullable=False),
        sa.Column('authenticated', sa.BOOLEAN(), autoincrement=False,
                  nullable=False),
        sa.PrimaryKeyConstraint('id', name='users_pkey'),
        sa.UniqueConstraint('user_id', name='users_user_id_key'),
        sa.UniqueConstraint('username', name='users_username_key')
    )
    # ### end Alembic commands ###
